myapp/urls.py
from django.urls import path
from . import views
# This is called namespacing: When there are more than one apps,
# If urlpatterns in different apps have the same name, conflict will occur.
# So to avoid it, we use namespacing as follows:
app_name = 'myapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('items/', views.item),
    # The name attribute is used for dynamic urls in html page
    path('<int:id>/', views.detail, name="detail"), 
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

myapp/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name
    
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField()
    item_price = models.IntegerField()
    

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item

# Create your views here.
def index(request):
    # Fetch data from the database
    item_list = Item.objects.all()
    # Create context to pass data to template
    context = {
        'item_list': item_list
    }
    # Passing the context object to template
    return render(request, "myapp/index.html", context)

def detail(request, id):
    item = Item.objects.get(id=id)
    context = {
        'item': item
    }
    return render(request, "myapp/detail.html", context)


def item(request):
    return HttpResponse("<h1>This is an item view</h1>")

myapp/templates/myapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Menu</title>
</head>
<body>
    <h1>
        {{item.item_name}}
        {{item.item_price}}
        {{item.item_desc}}
    </h1>
</body>
</html>

myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Menu</title>
</head>
<body>
    <h1>Hello</h1>
    <ul>
        {% for item in item_list %}
            <li>
                {% comment %} Using the names from urlpatterns for dynamic urls {% endcomment %}
                <a href="{% url 'myapp:detail' item.id %}">
                    {{item.item_name}} - {{item.item_price}} - {{item.item_desc}}
                </a>
            </li>
        {% endfor %}
    </ul>
        
</body>
</html>